#BOOTMAGIC_ENABLE = yes	# Virtual DIP switch configuration
EXTRAKEY_ENABLE = yes	# Audio control and System control
CONSOLE_ENABLE = yes	# Console for debug
COMMAND_ENABLE = yes    # Commands for debug and configuration
SLEEP_LED_ENABLE = no  # Breathing sleep LED during USB suspend
NKRO_ENABLE =no	    # USB Nkey Rollover
CUSTOM_MATRIX = no 	# Custom matrix file
MOUSEKEY_ENABLE = no
DEBUG_MATRIX = yes
DEFAULT_FOLDER = handwired/ms_sculpt_mobile/8x18_arm
